# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release 🚀

# Dynamically set the run name to include the type of branch (feature or bugfix), branch name, and the user
run-name: "Release: ${{ github.head_ref }} by @${{ github.actor }} run #${{ github.run_number }} attempt #${{ github.run_attempt }}"

on:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**'
      - '.editorconfig'
      - '.gitignore'
      - '.gitattributes'
      - '.vscode/**'
      - '.dockerignore'

env:
  DOTNET_VERSION: '8.0.x'
  BUILD_CONFIGURATION: 'Release'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 📦
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies 📂
      run: dotnet restore

    - name: Build 🧱
      run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
      
    - name: Test  🧪
      run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }} --no-build --verbosity normal